sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-020
env:
  global:
    -
      # LTD_AWS_ID
      secure: UtEfJxC5fKmq2ez+6fM+JRt3hUOdHASBwa+A9I1DdamQsV5B0K2out6fQMy1NLYfo2Pt3Sbsxf/HmVhSS+QLBDuEM9KzAFjgk2it/G8PV31PMZAHV5zPGA1Y9tdy43kqgFhnDA0SmvxjswEJdJdQ6nlWuq8i4Unk7kKK920Mhd4LAOjr9YaoGx9K24uS9GmobXRS1nO5XOIgDmJoJCWyaN/yFJlld13QW/L4GYWcdzjXdP3mwovbrQ/4xLNIEL5nst8S4FS5QtVY1IK8OfdPaQkkpCcn5ioukTICDEUbyIC45kGqPwdB/pE0bCXRwCbvPPNxdghrnDgWSJ63v+kfOkrPG9EtWO+IBrFPwah+6aJm+3yDsy0xpiMOMvxdkI0slc8fGHCYibJi68QJjLLH0mNJNEecpNFkLn7XVTGbtYwEEtsCvXp+EKp/FUtmkdwMcaACWgiBD1t2LLXZ1ZP2Ehkal5O0mggE7yS9nk5481M+bt2psmWeqyg+m05u0MDIoMVmNis8i479EkSBc4TPMcQhEPmswqBbarc7R7G6v2eHYUw5jcXvmocyp+0HpIux9DeXoDDy7NS1lFLQBj8acxltN9f4Q45kTmlYc02uarlMGsNvvysFKhVxF50zjyYJ9m+iNF71hJQNaN0zs0L70bSruqcL/eJlx/8IshyEsrw=
    -
      # LTD_AWS_SECRET
      secure: ZZfP0ruZWv0NI7cpxiIVIMiwcrw44NwbsTw3hH6KKaKLGRsRMCCTIRjto6Fps8NsMQxBEOlk9j3jfaH0FaUUAnPqxOaDhE7Vh9gqzVOQAF47DgmpWnlJf0NQnRk9sWoeQchPF89XSVTpWyA3UvDZ1hXqMG20Y60jO3uzpmZWohI1fMSAv3faNmIAGptttOJlyA/9bI+cghHHT4Alt3nvvxdYOl5k10vQUAMnGUvKDarkV0+adbryA/oPvqO4MktHHGde2mN55C8CTjT2ttZliNhtEpY3E6IbWSeoi9dkqPhhMGnUZHG9NfmRfH6qTfiq90Dqg7QIDSkiH9JYQAk5MWebIJlvPmVidvCSnFxWjhwZ4znVjJ0qtwOgdKixnEaQ0nY6Nk9z3DhpSYw+OCXO/h7FFUWyCaeg0APztPXe8Cax3w9ZtxgPZuJf45HnLUZf/tzIuSqXdn5dzv7my4T4DMa/GR0+yUlclQ83hZ/AMzs3dt5UgibEFuBHhjCv7TKTq7KZKyuhaR4i3Ewq+mjAUnFbyNyZZAyCsZxX0AQ5hm+zF9LAiZFXy++u28dXejqayF4qs5LhlZ0vchi3xCMl2M7YuggMx4Dfyxy+6szFXd/Ja7SQ8uO+yD4TWb/IPpRJuTVXLgKAPW1gH/F0uJrE6pLNzDt/+q3myM+VTfcfRBc=
    -
      # LTD_USERNAME
      secure: aXfj0JmfsryRv/QJUJtyR6cGLJ274N2KKElASL9rxq+FB7St0+ANxhxszXwwCRzYyebipgcSfeEeTP/6poJXqMXG51B2oUZGvhWXwO/pIGiL/BA8aI4oyY2MMFFhjiOLx65LX0P/wmRjGoSBRL1PFwqKjYC67Z5InrKsJN121pEai/VY28aZDUWEDP17hCkW7TjX0UrqbyNK75sDRnSJaSvnA5nNNAI9Koqh8RdndLXvUHI/844JYWpWznF84aknvmy+gLVyqm8Mb12BMC3bg2MBv4nsBBBd8oLdTOWBZtNx2NCfZ8P7DUcsdBz7SFlej7RD2LuERJQ3Fjn7Z2kmPQbt5OXmemkmk/cYsoE7Pvz9fB1PCIITuengWg+i0UeSkvk1X6lddlDvjAwItYcF5T4D8brAaV0x1oWqsgIbczoXHA6xwXr0O0x+v2fLcU9xp3m5A24GJMnKl/Xgvy4ItdaJr1zd/88MUryNnLvs6h/l+pyc56vLq1U+tc+CVAp5xVdR+BFHbDZq/2rf68rHQs4V5/HBvQzJr39Q3q5pR3N7CwFNan130aRLNkchSVX+pQ1InXAaCzCqmqSVTlAk0wkYMUqBcn4ZnWtS0fllFDK8RlsXkr2hGYzc2tR884em7FxnFLNENSPZgSl6+9j5xSEud0a//sprX6r2otde0YE=
    -
      # LTD_PASSWORD
      secure: r1GOoJb6lCX6l+4p6UNvEOOm6Uy6sMBb8NfMs7HeKbohU2/lRNJRg2uqGcNxHtmFS7i2XdLO1ff8ZhKf2pGEoBj5CeNBsvylpXSIhHme9K5f253Cd7083AmiB4UfCHpMMduvxTLKxhw5l8gNhoPMSMEnUr0KY4vDU0nPQ1MxDXpUdl69vBzHCUOccXfquhVHCg0KLf7sGl+C8L6cXu125c4skntVaurY0rnuwMuYBqkAV7juhMyMQj+Vh+WidLSrUTnCdds/mdkQNQTmerCi3vIwGqE1F7CWSihtHU33T5F2ODaYOcW1biacny5ImpNfTP3qAeLy5+ZeUz4B+uO3fNsRJ05FJmW0waV1w2UymWCttF1qKhVCg9bODTBI0yDZEzgp7Qta3Esu2y9W6t+xpMQc94kElxiZzBXxsH0zxbwaipFluof00AA877X0scOhySMDwkUPFpM35i/sHwCMIIPBHAPFLJ/7rLYHwfw/ORE4hpOmIlWy7AXZMmUjgqTBPqoKNf0m1fe+G0FrDzJW8pkYjj0K102fsGYlOYY9UBxygb912QBVKVUMNSn446B9h+z7zGMzmE8/YPvmMyof3c73DOXBufHbPSpgjA9goPJWeB4dt5s5LqMl1Gyu/6KxDkk0tko0gQkDBbdZBDThl8ZUHuzYHmIX/aqf5CjxqqQ=
